
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)

install.packages(c("coda","mvtnorm","devtools","loo", "here", "foreign","dagitty", "posterior","bayesplot"))
devtools::install_github("rmcelreath/rethinking")

install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
install_cmdstan(cores = 2) # make sure you have C++ headers etc installed - e.g. COmmand Line Tools on MacoS
# see https://mc-stan.org/cmdstanr/articles/cmdstanr.html for mor

library(rethinking) # the sw for model specification (it then uses cmdstan)
library(foreign) # need to load funky data format
library(here) # make sure working dir is the same all the time
library(posterior)
library(bayesplot)
set.seed(100)
```

```{r}
setwd("~/SENG480B")
f <- read.arff("data/nasa93.arff")
f <- f[c(3, 6, 10, 15, 17, 24)]
summary(f)
```

```{r}
# sample randomly from a log-normal()
max(rlnorm(1e5, 0, 2.2))
```

```{r m0, message=FALSE, warning=FALSE, results='hide'}
m0 <- ulam(
  alist(
    act_effort ~ poisson(lambda),
    log(lambda) <- alpha, # log link
    alpha ~ normal(0, 2.2)
  ), data = f, cores = 4, chains = 4, cmdstan = TRUE, log_lik = TRUE, iter = 5e3
)
```


```{r}
precis(m0)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='hide', fig.align='center'}
trankplot(m0)
```

```{r}
plot(precis(m0, depth = 2, prob = 0.95))
```

```{r}
var(f$act_effort)
mean(f$act_effort)
```

```{r loo, warning=FALSE, message=FALSE, fig.align='center'}
(loo_est <- compare(m0, m1, m2, func=LOO))
```

```{r}
loo_est[2,3] + c(-1,1) * loo_est[2,4] * 1.96
```

```{r}
plot(precis(m2, depth = 2, pars = "a_lang", prob = 0.95))
```
